### ISSUE TITLE
struct_name column unused?

### ISSUE THREAD

**Issue by DavidOliver** [Qqwy/elixir_revisionair_ecto#42]
Hi. Me again, with another niggly and unimportant issue. ;)

I noticed that the `struct_name` column which is created via the given migration doesn't seem to be populated, and a search for it in the code doesn't seem to turn anything up. Is it a left-over from development, and should it be removed from the migration?

**Comment by Qqwy** [comment]
Great find!
I do not remember what its purpose was; it definitely seems like something that was leftover. It is not used in the current implementation.

It can be removed from your migration, and I'll be removing it from the examples in the documentation for the next version :slightly_smiling_face:
